<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\jogador.domain\jogador.domain.csproj" />
    <ProjectReference Include="..\..\Shared\jogador.communication\jogador.communication.csproj" />
    <ProjectReference Include="..\..\Shared\jogador.exception\jogador.exception.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
