<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Update="ResourceMessagesException.resx">
      <StronglyTypedLanguage>CSharp</StronglyTypedLanguage>
      <StronglyTypedNamespace>jogador.exception</StronglyTypedNamespace>
      <StronglyTypedClassName>ResourceMessagesException</StronglyTypedClassName>
      <StronglyTypedFileName>$(IntermediateOutputPath)ResourceMessagesException.Designer.cs</StronglyTypedFileName>
      <PublicClass>true</PublicClass>
    </EmbeddedResource>
  </ItemGroup>
</Project>
